### ISSUE TITLE
Broken redirections in .htaccess

### ISSUE THREAD

**Issue by pcanterino** [viewvc/viewvc.org#2]
Since tigris.org was shut down, the [.htaccess file](https://github.com/viewvc/viewvc.org/blob/master/.htaccess) of viewvc.org contains some broken redirections.

I don't know if these redirections are still required, but you could perhaps use https://htmlpreview.github.io/ to achieve this on GitHub.

**Comment by cmpilato** [comment]
Thanks for the report and the excellent suggestion of using htmlpreview.github.io.  I've incorporated precisely that suggestion.
